### ISSUE TITLE
Could not find 'reel-io' (~> 0.0.0.pre) - did find: [reel-io-0.0.0.pre] (Gem::MissingSpecVersionError)

### ISSUE THREAD

**Issue by watsy0007** [celluloid/reel-dsl#7]
```
/Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'reel-io' (~> 0.0.0.pre) - did find: [reel-io-0.0.0.pre] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/wat/.rvm/gems/ruby-2.3.0:/Users/watsy/.rvm/gems/ruby-2.3.0@global', execute `gem env` for more information
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:200:in `rescue in try_activate'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/wat/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from examples/hello_world-standalone.rb:1:in `<main>'
```

**Comment by digitalextremist** [comment]
This gem, and the referenced gem ( `reel-io` ) are in a stage before release.
